In [1]:
import numpy as np

In [2]:
X = np.array([[1,0,1,0], [1,0,1,1], [0,1,0,1]])
y = np.array([[1],[1],[0]])

In [3]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
y

array([[1],
       [1],
       [0]])

In [5]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1

In [6]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def derivativeSigmoid(x):
  return x * (1 - x)

In [7]:
weightHidden = np.random.uniform(size=(input_neurons, hidden_neurons))
weightOutput = np.random.uniform(size=(hidden_neurons, output_neurons))
biasHidden = np.random.uniform(size=(1, hidden_neurons))
biasOutput = np.random.uniform(size=(1, output_neurons))

In [8]:
weightHidden

array([[0.20569817, 0.59202758, 0.90504767],
       [0.09477154, 0.7685256 , 0.20820355],
       [0.69974009, 0.73497072, 0.08907666],
       [0.2476866 , 0.91468083, 0.76665341]])

In [9]:
weightOutput

array([[0.20763479],
       [0.94638492],
       [0.73792253]])

In [25]:
epochs = 1000
alpha = 0.01

In [10]:
fx = np.dot(X, weightHidden) + biasHidden

In [11]:
fx

array([[1.55556418, 1.46443314, 1.89222338],
       [1.80325079, 2.37911397, 2.65887679],
       [0.99258407, 1.82064126, 1.87295601]])

In [12]:
hiddenLayer = sigmoid(fx)

In [13]:
hiddenLayer

array([[0.82571592, 0.81220978, 0.86900883],
       [0.85854419, 0.91522071, 0.934556  ],
       [0.72959802, 0.86064306, 0.86679994]])

In [14]:
fx1 = np.dot(hiddenLayer, weightOutput) + biasOutput
outputLayer = sigmoid(fx1)

In [15]:
outputLayer

array([[0.87023595],
       [0.88652428],
       [0.8729498 ]])

In [16]:
# Error
# Slope
# Delta
errorOutput = y - outputLayer

In [17]:
errorOutput

array([[ 0.12976405],
       [ 0.11347572],
       [-0.8729498 ]])

In [18]:
slopeOutput = derivativeSigmoid(outputLayer)

In [19]:
slopeOutput

array([[0.11292534],
       [0.10059898],
       [0.11090845]])

In [20]:
deltaOutput = errorOutput * slopeOutput

In [21]:
deltaOutput

array([[ 0.01465365],
       [ 0.01141554],
       [-0.09681751]])

In [23]:
errorHidden = deltaOutput.dot(weightOutput.T)

In [24]:
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden

In [26]:
weightOutput = weightOutput - hiddenLayer.T.dot(deltaOutput) * alpha

In [27]:
weightOutput

array([[0.20812217],
       [0.94699468],
       [0.73852772]])

In [28]:
weightHidden = weightHidden -  X.T.dot(deltaHidden) * alpha

In [29]:
biasOutput = biasOutput - np.sum(deltaOutput) * alpha
biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [36]:
weightHidden = np.random.uniform(size=(input_neurons, hidden_neurons))
weightOutput = np.random.uniform(size=(hidden_neurons, output_neurons))
biasHidden = np.random.uniform(size=(1, hidden_neurons))
biasOutput = np.random.uniform(size=(1, output_neurons))

epochs = 15000
alpha = 0.01

for i in range(epochs):
  # Feedforward
  fx = np.dot(X, weightHidden) + biasHidden
  hiddenLayer = sigmoid(fx)
  fx1 = np.dot(hiddenLayer, weightOutput) + biasOutput
  outputLayer = sigmoid(fx1)

  # Backpropagation
  # Error
  # Slope
  # Delta
  errorOutput = outputLayer - y
  slopeOutput = derivativeSigmoid(outputLayer)
  deltaOutput = errorOutput * slopeOutput

  errorHidden = deltaOutput.dot(weightOutput.T)
  slopeHidden = derivativeSigmoid(hiddenLayer)
  deltaHidden = errorHidden * slopeHidden

  # Optimization
  weightOutput = weightOutput - hiddenLayer.T.dot(deltaOutput) * alpha
  weightHidden = weightHidden -  X.T.dot(deltaHidden) * alpha
  biasOutput = biasOutput - np.sum(deltaOutput) * alpha
  biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [37]:
outputLayer

array([[0.9527918 ],
       [0.92869834],
       [0.09588762]])